spring:
  redis:
    host: 192.168.111.140
    port: 6379
server:
  port: 8084
zuul:
  routes:
    product:
      path: /myProduct/**
      serviceId: cloud-product
  sensitive-headers:
management:
  security:
    enabled: false
